
#
# Sets if automatic AFK-ing of players is enabled
#
autoAFkEnabled = true

#
# Delay until an unmoving player is automatically set as AFK
#
autoAfkDelay = "10m"

#
# Maximum time a player is allowed to be offline
# If this time is surpssed by a user in a given day, the action specified by
# 'allowedTimeSurpassed' is performed
#
allowedAfkTime = "1h"

#
# What action is taken when the maximum 'allowedAfkTime' is surpassed by a player
#
# Possible values:
# - 'none': Nothing happens :I
# - 'kick': The player is kicked
# - 'tempban' The player is tempbanned until 00:00:00 server time
# - 'permban': lmao
#
allowedTimeSurpassed = "kick"