
#
# Sets if automatic AFK-ing of players is enabled
#
autoAfkEnabled = true

#
# Delay until an unmoving player is automatically set as AFK
#
autoAfkDelay = "10m"

#
# Maximum time a player is allowed to be offline
# If this time is surpssed by a user in a given day, the action specified by
# 'allowedTimeSurpassed' is performed
#
allowedAfkTime = "1h"

#
# The minimum amount of time a player will be tempbanned for, if
# allowedTimeSurpased is set to "tempban"
#
minTempbanTime = "4h"

#
# What action is taken when the maximum 'allowedAfkTime' is surpassed by a player
#
# Possible values:
# - "none": Nothing happens :I
# - "kick": The player is kicked
# - "tempban": The player is tempbanned until 00:00:00 server time or for minTempbanTime if the next
#              day is less than minTempbanTime away
# - "permban": lmao
#
allowedTimeSurpassed = "kick"