# Interval at which announcements are broadcast
interval = "5m"

# Sets the order the announcements are announced in
# Possible values:
# - 'incrementing' Goes through each announcement in order
# - 'random' Goes through announcements in a random order, may repeat
# - 'shuffle' Goes through all announcements in a random order without repetition
# - 'decrementing' Goes through in reverse order from 'incrementing'
order = "incrementing"

# Format the announcements use, supports all default placeholders and the
# '${message}' placeholder
format = "${prefix} ${message}"

# Message array
# Supports all global placeholders
messages = []