#
# Waypoint marked as the 'spawn' region
#
spawnWaypoint = "Hazelguard"

#
# Waypoint sizes
#
adminWaypointSize = { x = 5, y = 5, z = 5 }
playerWaypointSize = { x = 5, y = 5, z = 5 }

#
# Hulksmashing poles global enabled/disabled state.
#
hulkSmashPoles = true

#
# Delay between a waypoint being marked for deletion, and
# the actual deletion of the waypoint
#
waypointDeletionDelay = "3d"

#
# Cooldown between users being able to do moveins
#
moveInCooldown = 0

#
# Duration for which a waypoint invite is valid
#
validCooldownTime = "10m"

#
# Plugin data auto save interval
#
autoSaveInterval = "30m"

#
# Max length of a waypoint name
#
maxNameLength = 20

#
# Range a player has to be in to a discoverable waypoint
# in order to discover a waypoint
#
discoveryRange = 50

#
# Banned waypoint names, case insensitive
#
bannedNames = [
  "region",
  "regionticket",
  "ticket",
  "region_ticket"
]